/**
 * كل نصوص الواجهة — عربي/إنجليزي.
 * ممنوع أي نص ثابت داخل المكوّنات. نفس مبدأ app_strings.dart بالتطبيق.
 */

export type Locale = "ar" | "en";

const values: Record<Locale, Record<string, string>> = {
  ar: {
    // عام
    app_name: "شاليهاتي",
    tagline: "احجز شاليهك بفلسطين بثلاث ضغطات",
    jd: "شيكل",
    per_night: "الليلة",
    guest_unit: "شخص",
    night_unit: "ليلة",
    nights_unit: "ليالٍ",
    confirm: "تأكيد",
    cancel: "إلغاء",
    back: "رجوع",

    // التنقل
    nav_home: "الرئيسية",
    nav_search: "تصفّح الشاليهات",
    nav_bookings: "حجوزاتي",
    nav_favorites: "المفضلة",
    nav_account: "حسابي",
    login: "تسجيل دخول",
    logout: "تسجيل خروج",
    guest_name: "زائر",

    // الرئيسية
    hero_title: "شاليهات فلسطين، كلها بمكان واحد",
    hero_sub: "من أريحا لرام الله لنابلس وبيت لحم — تصفّح، قارن، واحجز مباشرة.",
    search_hint: "ابحث عن شاليه أو مدينة",
    search_cta: "ابحث",
    featured: "شاليهات مميزة",
    featured_sub: "الأكثر حجزًا هالموسم",
    browse_by_type: "تصفح حسب النوع",
    browse_by_city: "تصفح حسب المدينة",
    view_all: "شوف الكل",
    how_it_works: "كيف بتحجز",
    step_search: "دوّر واختر",
    step_search_sub: "فلتر حسب المدينة والسعر والمرافق لحد ما تلاقي اللي بناسبك.",
    step_dates: "حدّد تواريخك",
    step_dates_sub: "التقويم بيوريك المتاح والمحجوز مباشرة، والسعر بيتحدّث لحظيًا.",
    step_book: "أكّد واستمتع",
    step_book_sub: "تأكيد فوري ورقم حجز، وتقدر تتواصل مع المالك مباشرة.",

    // البحث
    search_title: "تصفّح الشاليهات",
    filters: "الفلاتر",
    results_count: " شاليه",
    sort_by: "ترتيب حسب",
    sort_recommended: "المقترح",
    sort_price_asc: "الأرخص أولًا",
    sort_price_desc: "الأغلى أولًا",
    sort_capacity: "الأكبر سعة",
    empty_search_title: "لا توجد نتائج مطابقة",
    empty_search_sub: "جرّب توسيع بحثك أو تعديل الفلاتر",
    filter_city: "المدينة",
    filter_type: "النوع",
    filter_price: "مدى السعر",
    filter_guests: "عدد الأشخاص",
    filter_amenities: "المرافق",
    apply_filters: "تطبيق الفلاتر",
    reset_filters: "إعادة تعيين",
    city_all: "الكل",

    // المدن
    city_jericho: "أريحا",
    city_ramallah: "رام الله",
    city_nablus: "نابلس",
    city_bethlehem: "بيت لحم",
    city_tulkarm: "طولكرم",
    city_jenin: "جنين",
    city_hebron: "الخليل",
    city_qalqilya: "قلقيلية",

    // التفاصيل
    capacity_prefix: "يستوعب حتى ",
    description: "الوصف",
    amenities: "المرافق",
    prices: "الأسعار",
    weekdays: "أيام عادية",
    weekend: "نهاية الأسبوع",
    location: "الموقع",
    start_directions: "ابدأ التوجيه",
    book_now: "احجز الآن",
    save: "احفظ",
    saved: "محفوظ",
    share: "مشاركة",
    review_unit: "تقييم",
    host: "المضيف",
    hosted_by: "يستضيفك",
    hosting_since: "مستضيف منذ",
    verified_owner: "مالك موثّق",
    contact: "تواصل",
    rating_outstanding: "استثنائي",
    rating_excellent: "ممتاز",
    rating_very_good: "جيد جدًا",
    rating_good: "جيد",
    rating_fair: "مقبول",
    country_name: "فلسطين",

    // الحجز
    book_prefix: "احجز ",
    select_dates: "اختر التواريخ",
    check_in: "الوصول",
    check_out: "المغادرة",
    guests: "عدد الأشخاص",
    payment_method: "طريقة الدفع",
    pay_cash: "نقدًا عند الوصول",
    pay_cash_sub: "ادفع للمالك عند الوصول",
    pay_card: "بطاقة ائتمان",
    pay_card_sub: "فيزا / ماستركارد",
    price_summary: "ملخص السعر",
    service_fee: "رسوم الخدمة",
    total: "الإجمالي",
    confirm_booking: "تأكيد الحجز",
    legend_available: "متاح",
    legend_booked: "محجوز",
    legend_selected: "مختار",
    pick_dates_first: "اختر تواريخ الإقامة عشان نحسب السعر",

    // النتيجة
    booking_success_title: "تم تأكيد حجزك!",
    booking_success_sub: "الحجز مؤكد فورًا، بتنتظرك أيام حلوة",
    view_booking_details: "عرض تفاصيل الحجز",
    back_home: "الرجوع للرئيسية",
    booking_failed_title: "تعذّر إتمام الحجز",
    booking_failed_sub: "بعض هالتواريخ صارت محجوزة، اختر تواريخ ثانية",
    pick_other_dates: "اختر تواريخ ثانية",

    // الحساب
    my_bookings: "حجوزاتي",
    tab_upcoming: "القادمة",
    tab_past: "السابقة",
    empty_bookings_title: "لسّا ما عندك حجوزات",
    empty_bookings_sub: "ابدأ بتصفح الشاليهات واحجز أول عطلة إلك",
    browse_chalets: "تصفح الشاليهات",
    favorites: "المفضلة",
    empty_fav_title: "ما في شاليهات بالمفضلة",
    empty_fav_sub: "احفظ الشاليهات اللي عجبتك بالضغط على القلب",
    account: "حسابي",
    guest_prompt: "سجّل دخولك لتحفظ حجوزاتك ومفضلتك",
    booking_details: "تفاصيل الحجز",
    label_chalet: "الشاليه",
    label_dates: "التواريخ",
    label_nights: "عدد الليالي",
    label_guests: "عدد الأشخاص",
    label_payment: "طريقة الدفع",
    label_total: "المبلغ الإجمالي",
    label_booking_no: "رقم الحجز",
    contact_owner: "تواصل مع المالك",

    // تسجيل الدخول
    welcome_title: "أهلاً بك",
    welcome_sub: "أدخل رقم جوالك لتسجيل الدخول",
    country_code: "+970",
    phone_hint: "5X XXX XXXX",
    send_otp: "إرسال رمز التحقق",
    terms_note: "بمتابعتك أنت توافق على الشروط والأحكام وسياسة الخصوصية",
    otp_title: "أدخل الرمز المرسل",
    otp_sub: "أرسلنا رمزًا مكوّنًا من 4 أرقام إلى ",
    otp_resend_in: "إعادة الإرسال خلال ",
    otp_resend: "إعادة إرسال الرمز",
    otp_error: "الرمز غير صحيح، حاول مرة ثانية",

    // اللغة والفوتر
    menu_language: "اللغة",
    lang_ar: "العربية",
    lang_en: "English",
    menu_contact: "تواصل معنا",
    menu_terms: "الشروط والأحكام",
    footer_about: "منصّة فلسطينية لحجز الشاليهات مباشرة من المالك، بدون وسطاء.",
    footer_explore: "تصفّح",
    footer_help: "المساعدة",
    footer_rights: "جميع الحقوق محفوظة",
    demo_notice: "نسخة تجريبية — البيانات وهمية ولا يوجد دفع حقيقي.",

    // المرافق
    amenity_private_pool: "مسبح خاص",
    amenity_shared_pool: "مسبح مشترك",
    amenity_jacuzzi: "جاكوزي",
    amenity_ac: "تكييف",
    amenity_wifi: "واي فاي",
    amenity_bbq: "شواية",
    amenity_playground: "ملعب",
    amenity_games_room: "غرفة ألعاب",
    amenity_parking: "موقف سيارات",
    amenity_security: "حراسة",

    // الأنواع
    type_family: "عائلي",
    type_youth: "شبابي",
    type_events: "مناسبات",
    type_family_sub: "هدوء ومرافق أطفال",
    type_youth_sub: "أجواء وسهرات",
    type_events_sub: "أعراس وعزائم",

    // الحالات
    status_pending: "قيد الانتظار",
    status_confirmed: "مؤكد",
    status_cancelled: "ملغى",

    // لوحة الأدمن
    admin_title: "لوحة التحكم",
    admin_subtitle: "إدارة الشاليهات والمستخدمين",
    stat_chalets: "الشاليهات",
    stat_users: "المستخدمون",
    stat_bookings: "حجوزات الموسم",
    admin_chalets_table: "كل الشاليهات",
    admin_add_chalet: "إضافة شاليه جديد",
    admin_name_ar: "الاسم (عربي)",
    admin_name_en: "الاسم (إنجليزي)",
    admin_area_ar: "المنطقة (عربي)",
    admin_area_en: "المنطقة (إنجليزي)",
    admin_capacity: "السعة (عدد الأشخاص)",
    admin_price_weekday: "السعر — أيام عادية",
    admin_price_weekend: "السعر — نهاية الأسبوع",
    admin_description_ar: "الوصف (عربي)",
    admin_description_en: "الوصف (إنجليزي)",
    admin_owner_name_ar: "اسم المالك (عربي)",
    admin_owner_name_en: "اسم المالك (إنجليزي)",
    admin_submit: "إضافة الشاليه",
    admin_added_success: "تمت إضافة الشاليه بنجاح — وصار يظهر بالبحث والرئيسية",
    admin_users_table: "المستخدمون المسجّلون",
    admin_joined: "تاريخ التسجيل",
    admin_no_rating_yet: "بدون تقييم بعد",
    admin_view: "عرض",
    chalet_not_found_title: "الشاليه غير موجود",
    chalet_not_found_sub: "يمكن يكون الرابط قديم أو تم حذف الشاليه",
    admin_photos: "الصور",
    admin_add_photos: "إضافة صور",
    admin_video: "فيديو (اختياري)",
    admin_add_video: "إضافة فيديو",
    admin_remove: "حذف",
    admin_password_prompt: "لوحة التحكم محمية — أدخل كلمة السر للدخول",
    admin_password_placeholder: "كلمة السر",
    admin_password_error: "كلمة السر غلط",
    admin_unlock: "دخول",
    admin_contacts: "وسائل التواصل مع المالك",
    admin_add_contact: "إضافة وسيلة تواصل",
    admin_contact_value_placeholder: "رقم / رابط / إيميل",
    admin_payment_methods: "طرق الدفع المقبولة",
    admin_payment_methods_hint: "لازم تختار طريقة دفع واحدة على الأقل",
    contact_type_phone: "هاتف",
    contact_type_whatsapp: "واتساب",
    contact_type_email: "بريد إلكتروني",
    contact_type_facebook: "فيسبوك",
    contact_type_instagram: "إنستغرام",
    contact_type_telegram: "تيليجرام",
  },

  en: {
    app_name: "Chalets",
    tagline: "Book your Palestine getaway in three taps",
    jd: "ILS",
    per_night: "night",
    guest_unit: "guests",
    night_unit: "night",
    nights_unit: "nights",
    confirm: "Confirm",
    cancel: "Cancel",
    back: "Back",

    nav_home: "Home",
    nav_search: "Browse chalets",
    nav_bookings: "Bookings",
    nav_favorites: "Saved",
    nav_account: "Account",
    login: "Sign in",
    logout: "Log out",
    guest_name: "Guest",

    hero_title: "Palestine's chalets, all in one place",
    hero_sub: "From Jericho to Ramallah, Nablus and Bethlehem — browse, compare, and book direct.",
    search_hint: "Search chalets or cities",
    search_cta: "Search",
    featured: "Featured chalets",
    featured_sub: "Most booked this season",
    browse_by_type: "Browse by type",
    browse_by_city: "Browse by city",
    view_all: "View all",
    how_it_works: "How booking works",
    step_search: "Find your place",
    step_search_sub: "Filter by city, price and amenities until it fits what you need.",
    step_dates: "Pick your dates",
    step_dates_sub: "The calendar shows what's free and what's taken, and the price updates live.",
    step_book: "Confirm and go",
    step_book_sub: "Instant confirmation with a booking number, and a direct line to the owner.",

    search_title: "Browse chalets",
    filters: "Filters",
    results_count: " chalets",
    sort_by: "Sort by",
    sort_recommended: "Recommended",
    sort_price_asc: "Lowest price",
    sort_price_desc: "Highest price",
    sort_capacity: "Largest capacity",
    empty_search_title: "No matching results",
    empty_search_sub: "Try broadening your search or adjusting the filters",
    filter_city: "City",
    filter_type: "Type",
    filter_price: "Price range",
    filter_guests: "Guests",
    filter_amenities: "Amenities",
    apply_filters: "Apply filters",
    reset_filters: "Reset",
    city_all: "All",

    city_jericho: "Jericho",
    city_ramallah: "Ramallah",
    city_nablus: "Nablus",
    city_bethlehem: "Bethlehem",
    city_tulkarm: "Tulkarm",
    city_jenin: "Jenin",
    city_hebron: "Hebron",
    city_qalqilya: "Qalqilya",

    capacity_prefix: "Sleeps up to ",
    description: "Description",
    amenities: "Amenities",
    prices: "Pricing",
    weekdays: "Weekdays",
    weekend: "Weekend",
    location: "Location",
    start_directions: "Get directions",
    book_now: "Book now",
    save: "Save",
    saved: "Saved",
    share: "Share",
    review_unit: "reviews",
    host: "Host",
    hosted_by: "Hosted by",
    hosting_since: "Hosting since",
    verified_owner: "Verified owner",
    contact: "Contact",
    rating_outstanding: "Outstanding",
    rating_excellent: "Excellent",
    rating_very_good: "Very good",
    rating_good: "Good",
    rating_fair: "Fair",
    country_name: "Palestine",

    book_prefix: "Book ",
    select_dates: "Select dates",
    check_in: "Check-in",
    check_out: "Check-out",
    guests: "Guests",
    payment_method: "Payment method",
    pay_cash: "Cash on arrival",
    pay_cash_sub: "Pay the owner when you arrive",
    pay_card: "Credit card",
    pay_card_sub: "Visa / Mastercard",
    price_summary: "Price summary",
    service_fee: "Service fee",
    total: "Total",
    confirm_booking: "Confirm booking",
    legend_available: "Available",
    legend_booked: "Booked",
    legend_selected: "Selected",
    pick_dates_first: "Pick your dates to see the price",

    booking_success_title: "Your booking is confirmed!",
    booking_success_sub: "Confirmed instantly — great days ahead",
    view_booking_details: "View booking details",
    back_home: "Back to home",
    booking_failed_title: "Booking could not be completed",
    booking_failed_sub: "Some of these dates were just booked, please pick others",
    pick_other_dates: "Pick other dates",

    my_bookings: "My bookings",
    tab_upcoming: "Upcoming",
    tab_past: "Past",
    empty_bookings_title: "No bookings yet",
    empty_bookings_sub: "Browse chalets and book your first getaway",
    browse_chalets: "Browse chalets",
    favorites: "Saved",
    empty_fav_title: "Nothing saved yet",
    empty_fav_sub: "Tap the heart to save chalets you like",
    account: "My account",
    guest_prompt: "Sign in to keep your bookings and saved chalets",
    booking_details: "Booking details",
    label_chalet: "Chalet",
    label_dates: "Dates",
    label_nights: "Nights",
    label_guests: "Guests",
    label_payment: "Payment",
    label_total: "Total paid",
    label_booking_no: "Booking no.",
    contact_owner: "Contact owner",

    welcome_title: "Welcome",
    welcome_sub: "Enter your phone number to sign in",
    country_code: "+970",
    phone_hint: "5X XXX XXXX",
    send_otp: "Send verification code",
    terms_note: "By continuing you agree to the Terms and Privacy Policy",
    otp_title: "Enter the code",
    otp_sub: "We sent a 4-digit code to ",
    otp_resend_in: "Resend in ",
    otp_resend: "Resend code",
    otp_error: "Incorrect code, please try again",

    menu_language: "Language",
    lang_ar: "العربية",
    lang_en: "English",
    menu_contact: "Contact us",
    menu_terms: "Terms & conditions",
    footer_about: "A Palestinian platform for booking chalets directly from owners, with no middlemen.",
    footer_explore: "Explore",
    footer_help: "Help",
    footer_rights: "All rights reserved",
    demo_notice: "Demo build — data is placeholder and no real payment is taken.",

    amenity_private_pool: "Private pool",
    amenity_shared_pool: "Shared pool",
    amenity_jacuzzi: "Jacuzzi",
    amenity_ac: "Air conditioning",
    amenity_wifi: "Wi-Fi",
    amenity_bbq: "BBQ",
    amenity_playground: "Playground",
    amenity_games_room: "Games room",
    amenity_parking: "Parking",
    amenity_security: "Security",

    type_family: "Family",
    type_youth: "Youth",
    type_events: "Events",
    type_family_sub: "Quiet, with kids' facilities",
    type_youth_sub: "Music and late nights",
    type_events_sub: "Weddings and gatherings",

    status_pending: "Pending",
    status_confirmed: "Confirmed",
    status_cancelled: "Cancelled",

    admin_title: "Admin dashboard",
    admin_subtitle: "Manage chalets and users",
    stat_chalets: "Chalets",
    stat_users: "Users",
    stat_bookings: "Bookings this season",
    admin_chalets_table: "All chalets",
    admin_add_chalet: "Add a new chalet",
    admin_name_ar: "Name (Arabic)",
    admin_name_en: "Name (English)",
    admin_area_ar: "Area (Arabic)",
    admin_area_en: "Area (English)",
    admin_capacity: "Capacity (guests)",
    admin_price_weekday: "Price — weekdays",
    admin_price_weekend: "Price — weekend",
    admin_description_ar: "Description (Arabic)",
    admin_description_en: "Description (English)",
    admin_owner_name_ar: "Owner name (Arabic)",
    admin_owner_name_en: "Owner name (English)",
    admin_submit: "Add chalet",
    admin_added_success: "Chalet added — now visible in search and on the homepage",
    admin_users_table: "Registered users",
    admin_joined: "Joined",
    admin_no_rating_yet: "No ratings yet",
    admin_view: "View",
    chalet_not_found_title: "Chalet not found",
    chalet_not_found_sub: "This link may be old, or the chalet was removed",
    admin_photos: "Photos",
    admin_add_photos: "Add photos",
    admin_video: "Video (optional)",
    admin_add_video: "Add video",
    admin_remove: "Remove",
    admin_password_prompt: "This dashboard is protected — enter the password to continue",
    admin_password_placeholder: "Password",
    admin_password_error: "Incorrect password",
    admin_unlock: "Unlock",
    admin_contacts: "Owner contact methods",
    admin_add_contact: "Add contact method",
    admin_contact_value_placeholder: "Number / link / email",
    admin_payment_methods: "Accepted payment methods",
    admin_payment_methods_hint: "Pick at least one payment method",
    contact_type_phone: "Phone",
    contact_type_whatsapp: "WhatsApp",
    contact_type_email: "Email",
    contact_type_facebook: "Facebook",
    contact_type_instagram: "Instagram",
    contact_type_telegram: "Telegram",
  },
};

export function tr(locale: Locale, key: string): string {
  return values[locale]?.[key] ?? values.ar[key] ?? key;
}

/** كلمة وصفية للتقييم — نفس حدود Interhome الحقيقية (4.8 Outstanding, 4.5 Excellent, 4.4 Very good) */
export function ratingLabel(locale: Locale, value: number): string {
  const key =
    value >= 4.8
      ? "rating_outstanding"
      : value >= 4.5
        ? "rating_excellent"
        : value >= 4.0
          ? "rating_very_good"
          : value >= 3.5
            ? "rating_good"
            : "rating_fair";
  return tr(locale, key);
}

export const isRtl = (locale: Locale) => locale === "ar";
